CREATE TABLE USERS (
    USER_ID       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME      VARCHAR2(128) UNIQUE NOT NULL,
    PASSWORD      VARCHAR2(256) NOT NULL,
    LOCK_STATUS   VARCHAR2(16) DEFAULT 'UNLOCKED',
    FAILED_COUNT  NUMBER DEFAULT 0 NOT NULL,
    UPDATED_AT    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE LOCKOUT_EVENTS (
    ID            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME      VARCHAR2(128) NOT NULL,
    FAILED_COUNT  NUMBER NOT NULL,
    EVENT_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    RAW_EVENT     CLOB
);

INSERT INTO USERS (USERNAME, PASSWORD, LOCK_STATUS, FAILED_COUNT)
VALUES ('john', 'password123', 'UNLOCKED', 0);
COMMIT;
